### ISSUE TITLE
Some questions about the implementation of phase consistency loss

### ISSUE THREAD

**Issue by qianyuzqy** [donglao/PCEDA#10]
Hi, thanks for sharing the impressive work,  however, I got some trouble when understanding your implementation of phase consistency loss (Eq.5), in Line 140-143 of the file "PCEDA_Phase/models/cycle_gan_model.py". 

Q1. What is the intuition of using the amplitude ratio (w2) to reweight the cosine distance? I can understand that our final goal is to keep the phase consistency between the generated image with the real image. Thus, the tensor "cos" in Line 148 should be larger. But why do you impose the w2 constraint onto the cos?

Q2. Why do you calculate the amp2max in Line141, Line 142 in the dimension of H, and w, respectively? Is there any meaning behind it?

Thank you in advance, and looking forward to your reply.

**Comment by donglao** [comment]
Remark: the questions were answered through private emails and chats long ago. I'll paste them here:

cos*w2 is a weighting to the cosine, which means the higher the amp of a certain frequency is, the more weight it has in the phase consistency loss. For those frequencies that have smaller amp's, they do not matter much in terms of image generation. This is a simple trick to make training more stable, the code will run even if these lines are removed.
