### ISSUE TITLE
How would you define a white region

### ISSUE THREAD

**Issue by GaoN0801** [donglao/PCEDA#2]

**Comment by donglao** [comment]
Hi could you please specify what is the white region you are referring to?

**Comment by GaoN0801** [comment]
![m  n](https://user-images.githubusercontent.com/43678109/87848108-acdbcd80-c90f-11ea-8a4a-8594f8edad8c.png)


I'm sorry that I didn't notice the reply.I mean I don't know what ‘m<n’ means in formula 6,and ,is the white region with Yellow highlights a patch? If so, how do you define it

**Comment by donglao** [comment]
Here a white region refers to an over-exposed constant region in the sky. In this approximation we decompose the probability of a semantic label into a domain-dependent unary term and a domain-independent compatibility term. The latter is modeled by our ecological prior.
