### ISSUE TITLE
Some questions abput your Eq5

### ISSUE THREAD

**Issue by cedricgsh** [donglao/PCEDA#3]
I have two questions about your paper, mainly about Eq5
1)About the Eq 5. You said that using a single channel image x. Is this image x converted from RGB image to gray image , or use  Fourier Transform in every channel of a RGB image?
2)Does the j in Eq 5  mean the batch size or the number of channels in images?

**Comment by YanchaoYang** [comment]
1)About the Eq 5. You said that using a single channel image x. Is this image x converted from RGB image to gray image , or use  Fourier Transform in every channel of a RGB image?

- Yes, the FFT is performed on each channel of the RGB image.

2)Does the j in Eq 5  mean the batch size or the number of channels in images?

- j in Eq. 5 refers to the pixel location.

**Comment by cedricgsh** [comment]
Hi. I try to code your phase consistency by myself.However, the phase consistency implemented by me always leads to the loss value of cyclegan becomes 'nan' or ''inf'. Have you ever met this situation ? And how long will you make your codes about phase consistency available?

**Comment by YanchaoYang** [comment]
Please check the function named "get_phase_loss" in the file "PCEDA_Phase/models/cycle_gan_model.py" for our implementation of the phase consistency constraint. We now put a weight on the phase discrepancy for faster convergence but feel free to get rid of the weight, and it should not affect the final performance at convergence. 
For the nan issue, did you put a small epsilon in the denominator?
